camera_cam_3M_front:
    distortion_coeffs: [0.01384849, -0.00557897, -0.00019125, -0.000271]
    ext_quaternion_xyzw: [-0.5440991986513865, 0.5595174989342959, -0.44265244327794473,
        0.4415371387248132]
    ext_rpy_angles: [0.0, 0.0, 0.0]
    ext_translation: [2.0554651664686703, -0.0060563259766355515, 0.7719874730328724]
    focal_length: [570.58060231, 570.72929139]
    principal_point: [961.14455421, 764.61773278]
camera_cam_3M_left:
    distortion_coeffs: [1.47292340e-02, -5.18548001e-03, -1.40932415e-03, 8.43700503e-05]
    ext_quaternion_xyzw: [-0.7965188127280065, -0.009603685458836405, -0.014041396620831974,
        0.6043743784914373]
    ext_rpy_angles: [0.0, 0.0, 0.0]
    ext_translation: [0.6399342363722622, 0.5465569043094777, 0.7740377856469716]
    focal_length: [574.46857959, 574.74972345]
    principal_point: [959.90342689, 764.76712126]
camera_cam_3M_rear:
    distortion_coeffs: [1.68507092e-02, -6.39218326e-03, -9.88783168e-04, 5.17753632e-05]
    ext_quaternion_xyzw: [0.5485689430895782, 0.5374545758996817, -0.4504735800240545,
        -0.45528919075944285]
    ext_rpy_angles: [0.0, 0.0, 0.0]
    ext_translation: [-0.8120441845528125, -0.007706656679650613, 0.7790851763643512]
    focal_length: [572.8924374, 573.1017971]
    principal_point: [954.37442618, 763.51180296]
camera_cam_3M_right:
    distortion_coeffs: [0.01649807, -0.00668417, 0.00043621, -0.00045291]
    ext_quaternion_xyzw: [0.02445160333385736, 0.7852763089378643, -0.618635143035094,
        0.005813563216857122]
    ext_rpy_angles: [0.0, 0.0, 0.0]
    ext_translation: [0.6370943155534893, -0.5415086896102413, 0.767813168376311]
    focal_length: [571.88705254, 572.39154819]
    principal_point: [962.36612444, 767.3246358]
camera_cam_8M_wa_front:
    distortion_coeffs: [-0.319543334, 0.108013901, 6.43760453e-06, -9.69524494e-05,
        -0.0168342887]
    ext_quaternion_xyzw: [-0.495795, 0.499835, -0.499823, 0.504509]
    ext_rpy_angles: [-4, 89.5, -85.5]
    ext_translation: [1.946, 0.007, 0.998]
    focal_length: [1923.77263, 1924.71305]
    principal_point: [1914.74603, 1131.61475]